language: android
android:
  components:
    - platform-tools
    - build-tools-21.1.1
    - android-19
    - extra-android-support

install: ant


addons:
  apt:
    packages:
      - ant
jdk: oraclejdk8

notifications:
  email: false

before_install:
  - wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin > /dev/null 2>/dev/null
  - chmod +x android-ndk-r10e-linux-x86_64.bin && ./android-ndk-r10e-linux-x86_64.bin > /dev/null
  - mv android-ndk-r10e android-ndk
  - export PATH=`pwd`/android-ndk:`pwd`/android-sdk-linux/tools:`pwd`/android-sdk-linux/platform-tools:$PATH
  - git submodule update --init --recursive
script:
  - cp debug.keystore ~/.android/debug.keystore
  - sh gen-version.sh travis build
  - sh gen-config.sh test
  - python2 makepak.py xash-extras assets/extras.pak
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 -j2 APP_CFLAGS="-w" APP_ABI="armeabi-v7a-hard"
  - ant debug -Dtest.version=1
  - cp bin/xashdroid-debug.apk xashdroid-armv7.apk
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 clean
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 -j2 APP_CFLAGS="-w" APP_ABI="armeabi-v7a-hard" CFLAGS_OPT_ARM="-mthumb -mfpu=neon-vfpv4 -mcpu=cortex-a15 -ffast-math -pipe -mvectorize-with-neon-quad -DVECTORIZE_SINCOS -fPIC -DHAVE_EFFICIENT_UNALIGNED_ACCESS"
  - ant debug -Dtest.version=1
  - cp bin/xashdroid-debug.apk xashdroid-armv7-cortex-a7-a15.apk
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 -j2 APP_CFLAGS="-w" APP_ABI="armeabi"
  - ant debug -Dtest.version=1
  - cp bin/xashdroid-debug.apk xashdroid-armv6.apk
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 -j2 APP_CFLAGS="-w" APP_ABI="x86"
  - ant debug -Dtest.version=1
  - cp bin/xashdroid-debug.apk xashdroid-x86.apk
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 clean
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 -j2 APP_CFLAGS="-w" APP_ABI="armeabi-v7a-hard" CFLAGS_OPT_ARM="-mthumb -mfpu=vfpv3-d16 -mcpu=cortex-a9 -pipe -fPIC"
  - ant debug -Dtest.version=1
  - cp bin/xashdroid-debug.apk xashdroid-armv7-tegra2.apk
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 clean
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 -j2 APP_CFLAGS="-w" APP_ABI="armeabi" CFLAGS_OPT_ARMv5="-marm -march=armv5te -msoft-float -fPIC"
  - ant debug -Dtest.version=1
  - cp bin/xashdroid-debug.apk xashdroid-armv5.apk

after_script:
  - sh travis-upload.sh *.apk
  - sh travis-deploy.sh android-optimized *.apk
